# Generated by Django 6.1 on 2026-08-27 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('NTBK', 'Notebook'), ('CEL', 'Celular'), ('TBIT', 'Tablet/Tbit'), ('BAM', 'BAM'), ('OTRO', 'Otro')], max_length=10)),
                ('perifericos', models.TextField(blank=True, null=True)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('af', models.CharField(blank=True, max_length=100, null=True, verbose_name='Activo Fijo')),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ASIGNADO', 'Asignado'), ('DISPONIBLE', 'Disponible'), ('REPARACION', 'En Reparación'), ('BAJA', 'Dado de Baja')], default='DISPONIBLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilGenerico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('dpto_area', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ONPREMISE', 'Onpremise'), ('O365', 'Office 365')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('correo_corp', models.EmailField(max_length=254, unique=True)),
                ('dpto_area', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('ip_asignada', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario_red', models.CharField(max_length=50, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('gmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('pwd_gmail', models.CharField(blank=True, max_length=128, null=True)),
                ('vpn_cisco', models.BooleanField(default=False)),
                ('sif', models.BooleanField(default=False)),
                ('anexo_exterior', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='core.equipamiento')),
                ('usuario_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='core.usuario'),
        ),
    ]
