# Generated by Django 6.1 on 2026-08-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilgenerico',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
