# Generated by Django 6.1 on 2026-08-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_perfilgenerico_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilgenerico',
            name='dpto_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfilgenerico',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='perfilgenerico',
            name='tipo',
            field=models.CharField(default='ONPREMISE', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilgenerico',
            name='usuario',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
