# Generated by Django 6.1 on 2026-08-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_perfilgenerico_dpto_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilgenerico',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('LICENCIA', 'En Licencia'), ('BAJA', 'Dado de Baja')], default='ACTIVO', max_length=20),
        ),
    ]
