# Generated by Django 6.1 on 2026-08-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfilgenerico_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamiento',
            name='estado',
            field=models.CharField(choices=[('ASIGNADO', 'Asignado'), ('DISPONIBLE', 'Disponible'), ('REPARACION', 'En Reparación'), ('BAJA', 'Dar de Baja')], default='DISPONIBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilgenerico',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('LICENCIA', 'Licencia Medica'), ('BAJA', 'Dar de Baja')], default='ACTIVO', max_length=20),
        ),
    ]
