# Generated by Django 6.1 on 2026-08-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_equipamiento_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='anexo_exterior',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='pwd_gmail',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sif',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='vpn_cisco',
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'Activo'), ('LICENCIA', 'En Licencia'), ('BAJA', 'Dado de Baja')], default='ACTIVO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfilgenerico',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('LICENCIA', 'En Licencia'), ('BAJA', 'Dado de Baja')], default='ACTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='hostname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
