# Generated by Django 6.1 on 2026-08-27 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_usuario_anexo_exterior_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialequipo',
            old_name='fecha_asignacion',
            new_name='fecha_movimiento',
        ),
        migrations.RemoveField(
            model_name='equipamiento',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='equipamiento',
            name='perifericos',
        ),
        migrations.RemoveField(
            model_name='historialequipo',
            name='estado',
        ),
        migrations.AddField(
            model_name='historialequipo',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialequipo',
            name='usuario_nuevo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='anexo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password_gmail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='af',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='estado',
            field=models.CharField(default='ASIGNADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='historialequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipamiento'),
        ),
        migrations.AlterField(
            model_name='historialequipo',
            name='usuario_anterior',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='perfilgenerico',
            name='estado',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'Activo'), ('LICENCIA', 'En Licencia'), ('BAJA', 'Dado de Baja')], default='ACTIVO', max_length=20, null=True),
        ),
    ]
