# Generated by Django 6.1 on 2026-08-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_fecha_asignacion_historialequipo_fecha_movimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamiento',
            name='numero_telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
