# Generated by Django 6.1 on 2026-08-27 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_equipamiento_numero_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamiento',
            name='estado',
            field=models.CharField(choices=[('ASIGNADO', 'Asignado'), ('STOCK', 'Stock / Disponible'), ('MANTENCION', 'En Mantención'), ('BAJA', 'Dado de Baja')], default='ASIGNADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='historialequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='core.equipamiento'),
        ),
    ]
