# Generated by Django 6.1 on 2026-08-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_equipamiento_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamiento',
            name='hostname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
