# Generated by Django 6.1 on 2026-08-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_equipamiento_hostname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialequipo',
            options={'ordering': ['-fecha_movimiento']},
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialequipo',
            name='accion',
            field=models.CharField(default='MODIFICACION', max_length=50),
        ),
    ]
