# Generated by Django 6.1 on 2026-08-27 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_historialequipo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password_simi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='HistorialUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(default='MODIFICACION', max_length=50)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='core.usuario')),
            ],
            options={
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
