# Generated by Django 6.1 on 2026-08-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_usuario_password_simi_historialusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilgenerico',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password_gmail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password_simi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
