# Generated by Django 6.1 on 2026-08-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_perfilgenerico_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='celular',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='perfilgenerico',
            name='tipo',
            field=models.CharField(default='ON PREMISE', max_length=20),
        ),
    ]
