# Generated by Django 6.1 on 2026-08-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_usuario_celular_alter_perfilgenerico_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamiento',
            name='icloud_cuenta',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='icloud_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='imei',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='pin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='tipo',
            field=models.CharField(choices=[('Notebook', 'Notebook'), ('Celular', 'Celular'), ('Tablet', 'Tablet'), ('BAM / Router', 'BAM / Router'), ('Mac', 'Mac')], default='Notebook', max_length=30),
        ),
        migrations.AlterField(
            model_name='perfilgenerico',
            name='tipo',
            field=models.CharField(default='On Premise', max_length=20),
        ),
    ]
