# Generated by Django 6.1 on 2026-08-28 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_equipamiento_icloud_cuenta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_ip', models.GenericIPAddressField(unique=True)),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('RESERVADA', 'Reservada'), ('DUPLICADA', 'Duplicada'), ('DESCONOCIDA', 'Desconocida'), ('ASIGNADA', 'Asignada')], default='LIBRE', max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ips', to='core.usuario')),
            ],
            options={
                'verbose_name': 'IP',
                'verbose_name_plural': 'IPs',
                'ordering': ['direccion_ip'],
            },
        ),
    ]
