# Generated by Django 6.1 on 2026-08-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='asignado_otro',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
