# Generated by Django 6.1 on 2026-08-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_ip_asignado_otro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password_vpn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='vpn_cisco',
            field=models.BooleanField(default=False),
        ),
    ]
