# Generated by Django 6.1 on 2026-08-31 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_usuario_password_vpn_usuario_sif_usuario_vpn_cisco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip', to='core.usuario'),
        ),
    ]
