# Generated by Django 6.1 on 2026-09-08 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_ip_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_anexo', models.CharField(max_length=10, unique=True)),
                ('exterior', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADO', 'Asignado')], default='DISPONIBLE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexo_asignado', to='core.usuario')),
            ],
            options={
                'ordering': ['numero_anexo'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_anterior', models.CharField(blank=True, max_length=150, null=True)),
                ('usuario_nuevo', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(default='MODIFICACION', max_length=50)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('anexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='core.anexo')),
            ],
            options={
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
