# Generated by Django 6.1 on 2026-09-09 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_migrar_anexos_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCGenerico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_local', models.CharField(max_length=150)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('hostname', models.CharField(max_length=100, unique=True)),
                ('dpto_area', models.CharField(blank=True, max_length=150, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=150, null=True)),
                ('activo_fijo', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.CharField(blank=True, max_length=50, null=True)),
                ('almacenamiento', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPCGenerico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(default='MODIFICACION', max_length=50)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='core.pcgenerico')),
            ],
            options={
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
