# Generated by Django 6.1 on 2026-09-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_pcgenerico_historialpcgenerico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamiento',
            name='tipo',
            field=models.CharField(choices=[('Notebook', 'Notebook'), ('Celular', 'Celular'), ('Tablet', 'Tablet'), ('BAM / Router', 'BAM / Router'), ('Mac', 'Mac'), ('Monitor', 'Monitor'), ('Adaptador', 'Adaptador'), ('Audífonos', 'Audífonos'), ('Teclado', 'Teclado'), ('Mouse', 'Mouse'), ('Docking', 'Docking'), ('Otro Periférico', 'Otro Periférico')], default='Notebook', max_length=30),
        ),
        migrations.AlterField(
            model_name='pcgenerico',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
