# Generated by Django 6.1 on 2026-09-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_equipamiento_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('hostname', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
                'ordering': ['hostname'],
            },
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
