# Generated by Django 6.1 on 2026-09-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_servidor_alter_equipamiento_numero_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamiento',
            name='accesorios',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
