# Generated by Django 6.1 on 2026-09-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_equipamiento_accesorios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamiento',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pcgenerico',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
