# Generated by Django 6.1 on 2026-09-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_equipamiento_numero_serie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcgenerico',
            name='almacenamiento',
        ),
        migrations.RemoveField(
            model_name='pcgenerico',
            name='ram',
        ),
        migrations.AddField(
            model_name='pcgenerico',
            name='teamviewer_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pcgenerico',
            name='activo_fijo',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
