# Generated by Django 6.1 on 2026-09-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_pcgenerico_almacenamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='estado',
            field=models.CharField(choices=[('LIBRE', 'Libre'), ('RESERVADA', 'Reservada'), ('ASIGNADA', 'Asignada')], default='LIBRE', max_length=20),
        ),
    ]
