# Generated by Django 6.1 on 2026-09-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_ip_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='password_simi',
        ),
    ]
