# Generated by Django 6.1 on 2026-09-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_usuario_password_simi'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialanexo',
            name='modificado_por',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historialequipo',
            name='modificado_por',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historialpcgenerico',
            name='modificado_por',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historialusuario',
            name='modificado_por',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
