# Generated by Django 6.1 on 2026-09-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_historialanexo_modificado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilgenerico',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
