# Generated by Django 6.1 on 2026-09-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_perfilgenerico_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ip_asignada',
        ),
    ]
