# Generated by Django 6.1 on 2026-09-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_security_hardening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='estado',
            field=models.CharField(choices=[('LIBRE', 'Libre'), ('RESERVADA', 'Reservada')], default='LIBRE', max_length=20),
        ),
    ]
