# Generated by Django 6.1 on 2026-09-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_portal_session_and_server_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilgenerico',
            options={'ordering': ['departamento__nombre', 'subarea__nombre', 'nombre', 'usuario']},
        ),
    ]
