# Generated by Django 6.1 on 2026-09-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_perfilgenerico_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='anexo',
            index=models.Index(fields=['estado', 'numero_anexo'], name='idx_anexo_estado_num'),
        ),
        migrations.AddIndex(
            model_name='equipamiento',
            index=models.Index(fields=['tipo', 'estado'], name='idx_equipo_tipo_estado'),
        ),
        migrations.AddIndex(
            model_name='equipamiento',
            index=models.Index(fields=['usuario', 'tipo'], name='idx_equipo_usr_tipo'),
        ),
        migrations.AddIndex(
            model_name='ip',
            index=models.Index(fields=['estado', 'direccion_ip'], name='idx_ip_estado_dir'),
        ),
        migrations.AddIndex(
            model_name='perfilgenerico',
            index=models.Index(fields=['estado', 'departamento'], name='idx_perfil_estado_dpto'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['estado', 'departamento'], name='idx_usr_estado_dpto'),
        ),
    ]
