# Generated by Django 6.1 on 2026-09-24 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_anexo_idx_anexo_estado_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcgenerico',
            name='ip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pc_generico', to='core.ip'),
        ),
    ]
