# Generated by Django 6.1 on 2026-09-24 17:53

import django.db.models.deletion
from django.db import migrations, models


def backfill_ip_assignments(apps, schema_editor):
    IP = apps.get_model('core', 'IP')
    Usuario = apps.get_model('core', 'Usuario')
    Servidor = apps.get_model('core', 'Servidor')
    PCGenerico = apps.get_model('core', 'PCGenerico')
    AsignacionIP = apps.get_model('core', 'AsignacionIP')
    HistorialAsignacionIP = apps.get_model('core', 'HistorialAsignacionIP')

    users = {
        item.pk: item.nombre_completo
        for item in Usuario.objects.only('pk', 'nombre_completo')
    }
    servers = {
        item.ip_id: (item.pk, item.hostname)
        for item in Servidor.objects.exclude(ip_id=None).only('pk', 'ip_id', 'hostname')
    }
    pcs = {
        item.ip_id: (item.pk, item.hostname)
        for item in PCGenerico.objects.exclude(ip_id=None).only('pk', 'ip_id', 'hostname')
    }

    assignments = []
    history = []
    normalize_reserved_ids = []
    normalize_free_ids = []

    for ip in IP.objects.all().iterator(chunk_size=500):
        server = servers.get(ip.pk)
        pc = pcs.get(ip.pk)
        related_owners = sum(bool(item) for item in (ip.usuario_id, server, pc))
        if related_owners > 1:
            raise RuntimeError(
                f'La IP {ip.direccion_ip} tiene más de un propietario relacionado.'
            )

        assignment = None
        owner_id = None
        owner_name = None
        if ip.usuario_id:
            owner_id = ip.usuario_id
            owner_name = users.get(owner_id) or f'Usuario #{owner_id}'
            assignment = AsignacionIP(
                ip_id=ip.pk,
                tipo='USUARIO',
                usuario_id=owner_id,
            )
        elif server:
            owner_id, owner_name = server
            assignment = AsignacionIP(
                ip_id=ip.pk,
                tipo='SERVIDOR',
                servidor_id=owner_id,
            )
        elif pc:
            owner_id, owner_name = pc
            assignment = AsignacionIP(
                ip_id=ip.pk,
                tipo='PC_GENERICO',
                pc_generico_id=owner_id,
            )
        elif ip.asignado_otro and ip.asignado_otro.strip():
            owner_name = ip.asignado_otro.strip()
            assignment = AsignacionIP(
                ip_id=ip.pk,
                tipo='OTRO',
                detalle=owner_name,
            )

        if assignment:
            assignments.append(assignment)
            history.append(HistorialAsignacionIP(
                ip_id=ip.pk,
                direccion_ip=ip.direccion_ip,
                accion='MIGRACION',
                tipo=assignment.tipo,
                propietario_id=owner_id,
                propietario_nombre=owner_name,
                realizado_por='Migración 0042',
            ))
            if ip.estado != 'RESERVADA':
                normalize_reserved_ids.append(ip.pk)
        elif ip.estado == 'RESERVADA':
            normalize_free_ids.append(ip.pk)

    AsignacionIP.objects.bulk_create(assignments, batch_size=500)
    HistorialAsignacionIP.objects.bulk_create(history, batch_size=500)
    if normalize_reserved_ids:
        IP.objects.filter(pk__in=normalize_reserved_ids).update(estado='RESERVADA')
    if normalize_free_ids:
        IP.objects.filter(pk__in=normalize_free_ids).update(estado='LIBRE')


def reverse_ip_assignments(apps, schema_editor):
    apps.get_model('core', 'HistorialAsignacionIP').objects.all().delete()
    apps.get_model('core', 'AsignacionIP').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_pcgenerico_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('USUARIO', 'Usuario'), ('SERVIDOR', 'Servidor'), ('PC_GENERICO', 'PC Genérico'), ('OTRO', 'Otro dispositivo o servicio')], max_length=20)),
                ('detalle', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_activa', to='core.ip')),
                ('pc_generico', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_ip_activa', to='core.pcgenerico')),
                ('servidor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_ip_activa', to='core.servidor')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_ip_activa', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Asignación IP activa',
                'verbose_name_plural': 'Asignaciones IP activas',
                'ordering': ['ip__direccion_ip'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('detalle__isnull', True), ('pc_generico__isnull', True), ('servidor__isnull', True), ('tipo', 'USUARIO'), ('usuario__isnull', False)), models.Q(('detalle__isnull', True), ('pc_generico__isnull', True), ('servidor__isnull', False), ('tipo', 'SERVIDOR'), ('usuario__isnull', True)), models.Q(('detalle__isnull', True), ('pc_generico__isnull', False), ('servidor__isnull', True), ('tipo', 'PC_GENERICO'), ('usuario__isnull', True)), models.Q(('detalle__isnull', False), ('pc_generico__isnull', True), ('servidor__isnull', True), ('tipo', 'OTRO'), ('usuario__isnull', True), models.Q(('detalle', ''), _negated=True)), _connector='OR'), name='ck_asignacion_ip_propietario_valido')],
            },
        ),
        migrations.CreateModel(
            name='HistorialAsignacionIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_ip', models.GenericIPAddressField()),
                ('accion', models.CharField(choices=[('ASIGNACION', 'Asignación'), ('LIBERACION', 'Liberación'), ('MIGRACION', 'Migración inicial')], max_length=20)),
                ('tipo', models.CharField(blank=True, choices=[('USUARIO', 'Usuario'), ('SERVIDOR', 'Servidor'), ('PC_GENERICO', 'PC Genérico'), ('OTRO', 'Otro dispositivo o servicio')], max_length=20, null=True)),
                ('propietario_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('propietario_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('realizado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_asignaciones', to='core.ip')),
            ],
            options={
                'verbose_name': 'Historial de asignación IP',
                'verbose_name_plural': 'Historial de asignaciones IP',
                'ordering': ['-fecha_movimiento', '-pk'],
                'indexes': [models.Index(fields=['direccion_ip', '-fecha_movimiento'], name='idx_hist_ip_direccion_fecha')],
            },
        ),
        migrations.RunPython(
            backfill_ip_assignments,
            reverse_ip_assignments,
        ),
    ]
