# Generated by Django 6.1 on 2026-09-24 20:33

import django.db.models.deletion
from django.db import migrations, models


def normalize_key(value):
    return ' '.join(str(value or '').strip().split()).casefold()


def link_pc_organizational_units(apps, schema_editor):
    Departamento = apps.get_model('core', 'Departamento')
    SubArea = apps.get_model('core', 'SubArea')
    PCGenerico = apps.get_model('core', 'PCGenerico')

    departments = {
        item.nombre_normalizado: item.pk
        for item in Departamento.objects.only('pk', 'nombre_normalizado')
    }
    subareas = {}
    for item in SubArea.objects.only('pk', 'departamento_id', 'nombre_normalizado'):
        subareas.setdefault(item.nombre_normalizado, []).append(
            (item.pk, item.departamento_id)
        )

    pending = []
    for pc in PCGenerico.objects.filter(departamento__isnull=True).iterator(
        chunk_size=500
    ):
        key = normalize_key(pc.dpto_area)
        if not key:
            continue

        department_id = departments.get(key)
        if department_id:
            pc.departamento_id = department_id
            pending.append(pc)
            continue

        matching_subareas = subareas.get(key, [])
        if len(matching_subareas) == 1:
            pc.subarea_id, pc.departamento_id = matching_subareas[0]
            pending.append(pc)

    if pending:
        PCGenerico.objects.bulk_update(
            pending,
            ['departamento', 'subarea'],
            batch_size=500,
        )


def unlink_pc_organizational_units(apps, schema_editor):
    apps.get_model('core', 'PCGenerico').objects.update(
        departamento=None,
        subarea=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_centralize_ip_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcgenerico',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pcs_genericos', to='core.departamento'),
        ),
        migrations.AddField(
            model_name='pcgenerico',
            name='subarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pcs_genericos', to='core.subarea'),
        ),
        migrations.RunPython(
            link_pc_organizational_units,
            unlink_pc_organizational_units,
        ),
        migrations.AddIndex(
            model_name='pcgenerico',
            index=models.Index(fields=['departamento', 'subarea'], name='idx_pc_generico_dpto_sub'),
        ),
    ]
