# Generated by Django 6.1 on 2026-09-25

from django.db import migrations, models


NORMALIZED_FIELDS = (
    ('Usuario', 'nombre_completo', 'nombre_completo_normalizado', False, None),
    ('Usuario', 'usuario_red', 'usuario_red_normalizado', False, None),
    ('Usuario', 'correo_corp', 'correo_corp_normalizado', False, None),
    ('Servidor', 'hostname', 'hostname_normalizado', False, None),
    ('Equipamiento', 'numero_serie', 'numero_serie_normalizado', True, None),
    ('Equipamiento', 'af', 'af_normalizado', True, None),
    (
        'Equipamiento',
        'hostname',
        'hostname_computador_normalizado',
        True,
        ('Notebook', 'Mac'),
    ),
    ('PerfilGenerico', 'usuario', 'usuario_normalizado', False, None),
    ('PCGenerico', 'hostname', 'hostname_normalizado', False, None),
    ('PCGenerico', 'numero_serie', 'numero_serie_normalizado', True, None),
    ('PCGenerico', 'activo_fijo', 'activo_fijo_normalizado', True, None),
)


def normalize_key(value):
    return ' '.join(str(value or '').strip().split()).casefold()


def validate_normalized_uniqueness(apps, schema_editor):
    for model_name, source, _target, optional, allowed_types in NORMALIZED_FIELDS:
        model = apps.get_model('core', model_name)
        field_names = ['pk', source]
        if allowed_types:
            field_names.append('tipo')

        seen = {}
        for instance in model.objects.only(*field_names).iterator(chunk_size=500):
            enabled = not allowed_types or instance.tipo in allowed_types
            normalized = normalize_key(getattr(instance, source)) if enabled else ''
            value = normalized or (None if optional else '')
            if value is None:
                continue

            previous_pk = seen.get(value)
            if previous_pk is not None:
                raise RuntimeError(
                    'No se puede aplicar la unicidad normalizada de '
                    f'{model_name}.{source}: los registros {previous_pk} '
                    f'y {instance.pk} representan el mismo valor.'
                )
            seen[value] = instance.pk


def populate_normalized_identifiers(apps, schema_editor):
    for model_name, source, target, optional, allowed_types in NORMALIZED_FIELDS:
        model = apps.get_model('core', model_name)
        field_names = ['pk', source]
        if allowed_types:
            field_names.append('tipo')

        pending = []
        for instance in model.objects.only(*field_names).iterator(chunk_size=500):
            enabled = not allowed_types or instance.tipo in allowed_types
            normalized = normalize_key(getattr(instance, source)) if enabled else ''
            value = normalized or (None if optional else '')

            setattr(instance, target, value)
            pending.append(instance)

        if pending:
            model.objects.bulk_update(
                pending,
                [target],
                batch_size=500,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_pc_generico_departamento_subarea'),
    ]

    operations = [
        migrations.RunPython(
            validate_normalized_uniqueness,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_completo_normalizado',
            field=models.CharField(editable=False, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_red_normalizado',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo_corp_normalizado',
            field=models.EmailField(editable=False, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='hostname_normalizado',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='numero_serie_normalizado',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='af_normalizado',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='hostname_computador_normalizado',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfilgenerico',
            name='usuario_normalizado',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pcgenerico',
            name='hostname_normalizado',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pcgenerico',
            name='numero_serie_normalizado',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pcgenerico',
            name='activo_fijo_normalizado',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True),
        ),
        migrations.RunPython(
            populate_normalized_identifiers,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_completo_normalizado',
            field=models.CharField(editable=False, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_red_normalizado',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_corp_normalizado',
            field=models.EmailField(editable=False, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='hostname_normalizado',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='numero_serie_normalizado',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='af_normalizado',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='hostname_computador_normalizado',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='perfilgenerico',
            name='usuario_normalizado',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pcgenerico',
            name='hostname_normalizado',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pcgenerico',
            name='numero_serie_normalizado',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pcgenerico',
            name='activo_fijo_normalizado',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True),
        ),
    ]
