# Generated by Django 6.1 on 2026-09-25 11:14

from django.db import migrations, models


def validate_existing_assignment_states(apps, schema_editor):
    Anexo = apps.get_model('core', 'Anexo')
    Equipamiento = apps.get_model('core', 'Equipamiento')
    IP = apps.get_model('core', 'IP')

    valid_anexo = (
        models.Q(usuario__isnull=True, estado='DISPONIBLE')
        | models.Q(usuario__isnull=False, estado='ASIGNADO')
    )
    valid_equipment = (
        models.Q(
            usuario__isnull=True,
            fecha_asignacion__isnull=True,
            estado__in=['STOCK', 'MANTENCION', 'BAJA'],
        )
        | models.Q(
            usuario__isnull=False,
            estado__in=['ASIGNADO', 'MANTENCION', 'BAJA'],
        )
    )
    empty_other = (
        models.Q(asignado_otro__isnull=True)
        | models.Q(asignado_otro='')
    )
    valid_ip = (
        (
            models.Q(estado='LIBRE', usuario__isnull=True)
            & empty_other
        )
        | (
            models.Q(estado='RESERVADA', usuario__isnull=False)
            & empty_other
        )
        | (
            models.Q(
                estado='RESERVADA',
                usuario__isnull=True,
                asignado_otro__isnull=False,
            )
            & ~models.Q(asignado_otro='')
        )
    )

    invalid_counts = {
        'Anexo': Anexo.objects.exclude(valid_anexo).count(),
        'Equipamiento': Equipamiento.objects.exclude(valid_equipment).count(),
        'IP': IP.objects.exclude(valid_ip).count(),
    }
    invalid_counts = {
        model: count for model, count in invalid_counts.items() if count
    }
    if invalid_counts:
        detail = ', '.join(
            f'{model}: {count}' for model, count in invalid_counts.items()
        )
        raise RuntimeError(
            'Existen registros con estados de asignacion inconsistentes. '
            f'Corrigelos antes de migrar ({detail}).'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_normalized_unique_identifiers'),
    ]

    operations = [
        migrations.RunPython(
            validate_existing_assignment_states,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='anexo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'DISPONIBLE'), ('usuario__isnull', True)), models.Q(('estado', 'ASIGNADO'), ('usuario__isnull', False)), _connector='OR'), name='ck_anexo_asignacion_valida'),
        ),
        migrations.AddConstraint(
            model_name='equipamiento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado__in', ['STOCK', 'MANTENCION', 'BAJA']), ('fecha_asignacion__isnull', True), ('usuario__isnull', True)), models.Q(('estado__in', ['ASIGNADO', 'MANTENCION', 'BAJA']), ('usuario__isnull', False)), _connector='OR'), name='ck_equipo_asignacion_valida'),
        ),
        migrations.AddConstraint(
            model_name='ip',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'LIBRE'), ('usuario__isnull', True), models.Q(('asignado_otro__isnull', True), ('asignado_otro', ''), _connector='OR')), models.Q(('estado', 'RESERVADA'), ('usuario__isnull', False), models.Q(('asignado_otro__isnull', True), ('asignado_otro', ''), _connector='OR')), models.Q(('asignado_otro__isnull', False), ('estado', 'RESERVADA'), ('usuario__isnull', True), models.Q(('asignado_otro', ''), _negated=True)), _connector='OR'), name='ck_ip_estado_propietario'),
        ),
    ]
