# Generated by Django 6.1 on 2026-09-25

import django.db.models.deletion
from django.db import migrations, models


def validate_departments_are_present(apps, schema_editor):
    model_names = ('Usuario', 'PerfilGenerico', 'PCGenerico')
    missing = {}
    for model_name in model_names:
        model = apps.get_model('core', model_name)
        count = model.objects.filter(departamento__isnull=True).count()
        if count:
            missing[model_name] = count

    if missing:
        detail = ', '.join(
            f'{model}: {count}' for model, count in missing.items()
        )
        raise RuntimeError(
            'No se puede exigir departamento porque existen registros sin '
            f'relación organizacional ({detail}).'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_enforce_assignment_state_consistency'),
    ]

    operations = [
        migrations.RunPython(
            validate_departments_are_present,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='usuarios',
                to='core.departamento',
            ),
        ),
        migrations.AlterField(
            model_name='perfilgenerico',
            name='departamento',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='perfiles_genericos',
                to='core.departamento',
            ),
        ),
        migrations.AlterField(
            model_name='pcgenerico',
            name='departamento',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='pcs_genericos',
                to='core.departamento',
            ),
        ),
    ]
