# Generated by Django 6.1 on 2026-09-28 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_require_organizational_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor_hostname', models.CharField(max_length=100)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(default='MODIFICACION', max_length=50)),
                ('modificado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='core.servidor')),
            ],
            options={
                'ordering': ['-fecha_movimiento', '-pk'],
                'indexes': [models.Index(fields=['servidor', '-fecha_movimiento'], name='idx_hist_srv_fecha')],
            },
        ),
    ]
