# Generated by Django 6.1 on 2026-09-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_historialperfilgenerico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialusuario',
            options={'ordering': ['-fecha_movimiento', '-pk']},
        ),
        migrations.AddField(
            model_name='historialusuario',
            name='modulo_relacionado',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='historialusuario',
            name='objeto_relacionado_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddIndex(
            model_name='historialusuario',
            index=models.Index(fields=['usuario', '-fecha_movimiento'], name='idx_hist_usr_fecha'),
        ),
    ]
