# Generated by Django 5.2.17 on 2026-09-29 19:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_historialusuario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=25, unique=True)),
                ('anio', models.PositiveSmallIntegerField()),
                ('numero_correlativo', models.PositiveIntegerField()),
                ('tipo_movimiento', models.CharField(choices=[('ALTA', 'Alta de Activo'), ('ASIGNACION', 'Asignación'), ('REASIGNACION', 'Reasignación'), ('DEVOLUCION', 'Devolución'), ('CAMBIO', 'Cambio de equipo'), ('PRESTAMO', 'Préstamo'), ('INGRESO_REPARACION', 'Ingreso a reparación'), ('SALIDA_REPARACION', 'Salida de reparación'), ('BAJA', 'Baja')], max_length=30)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('GENERADA', 'Generada'), ('PENDIENTE_FIRMA', 'Pendiente de firma'), ('FIRMADA', 'Firmada'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], default='GENERADA', max_length=20)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('hash_verificacion', models.CharField(blank=True, default='', max_length=64)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Acta de Entrega y Custodia',
                'verbose_name_plural': 'Actas de Entrega y Custodia',
                'ordering': ['-fecha_emision', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='FolioContador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('tipo_documento', models.CharField(default='ATI', max_length=10)),
                ('ultimo_folio', models.PositiveIntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contador de Folio',
                'verbose_name_plural': 'Contadores de Folios',
            },
        ),
        migrations.CreateModel(
            name='MovimientoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ALTA', 'Alta de Activo'), ('ASIGNACION', 'Asignación'), ('REASIGNACION', 'Reasignación'), ('DEVOLUCION', 'Devolución'), ('CAMBIO', 'Cambio de equipo'), ('PRESTAMO', 'Préstamo'), ('INGRESO_REPARACION', 'Ingreso a reparación'), ('SALIDA_REPARACION', 'Salida de reparación'), ('BAJA', 'Baja')], max_length=30)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('ubicacion_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion_destino', models.CharField(max_length=100)),
                ('estado_fisico', models.CharField(choices=[('NUEVO', 'Nuevo'), ('SEMINUEVO', 'Seminuevo'), ('USADO', 'Usado'), ('DANADO', 'Dañado')], default='USADO', max_length=20)),
                ('estado_operativo_resultante', models.CharField(choices=[('ASIGNADO', 'Asignado'), ('STOCK', 'Stock / Disponible'), ('MANTENCION', 'En Mantención'), ('PRESTAMO', 'En Préstamo'), ('BAJA', 'Dado de Baja')], max_length=20)),
                ('accesorios_detalle', models.JSONField(blank=True, default=list)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ejecutado_por', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Movimiento de Activo',
                'verbose_name_plural': 'Movimientos de Activos',
                'ordering': ['-fecha_movimiento', '-pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='equipamiento',
            name='ck_equipo_asignacion_valida',
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='estado_fisico',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('SEMINUEVO', 'Seminuevo'), ('USADO', 'Usado'), ('DANADO', 'Dañado')], default='USADO', max_length=20),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='fecha_alta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='mac_address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='token_qr',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='ubicacion_actual',
            field=models.CharField(default='Bodega TI', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='centro_costo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut_normalizado',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ubicacion',
            field=models.CharField(blank=True, default='Casa Matriz - Quilicura', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='estado',
            field=models.CharField(choices=[('ASIGNADO', 'Asignado'), ('STOCK', 'Stock / Disponible'), ('MANTENCION', 'En Mantención'), ('PRESTAMO', 'En Préstamo'), ('BAJA', 'Dado de Baja')], default='ASIGNADO', max_length=20),
        ),
        migrations.AddIndex(
            model_name='equipamiento',
            index=models.Index(fields=['token_qr'], name='idx_equipo_token_qr'),
        ),
        migrations.AddConstraint(
            model_name='equipamiento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado__in', ['STOCK', 'MANTENCION', 'BAJA']), ('fecha_asignacion__isnull', True), ('usuario__isnull', True)), models.Q(('estado__in', ['ASIGNADO', 'MANTENCION', 'BAJA', 'PRESTAMO']), ('usuario__isnull', False)), _connector='OR'), name='ck_equipo_asignacion_valida'),
        ),
        migrations.AddField(
            model_name='actaentrega',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas', to='core.usuario'),
        ),
        migrations.AddField(
            model_name='actaentrega',
            name='usuario_ti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_emitidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='foliocontador',
            constraint=models.UniqueConstraint(fields=('anio', 'tipo_documento'), name='uniq_folio_anio_tipo'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='acta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.actaentrega'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.equipamiento'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='colaborador_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='core.usuario'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='colaborador_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='core.usuario'),
        ),
        migrations.AddIndex(
            model_name='actaentrega',
            index=models.Index(fields=['folio'], name='idx_acta_folio'),
        ),
        migrations.AddIndex(
            model_name='actaentrega',
            index=models.Index(fields=['colaborador', '-fecha_emision'], name='idx_acta_colab_fecha'),
        ),
        migrations.AddIndex(
            model_name='actaentrega',
            index=models.Index(fields=['estado', '-fecha_emision'], name='idx_acta_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='movimientoactivo',
            index=models.Index(fields=['activo', '-fecha_movimiento'], name='idx_mov_act_fecha'),
        ),
        migrations.AddIndex(
            model_name='movimientoactivo',
            index=models.Index(fields=['colaborador_destino', '-fecha_movimiento'], name='idx_mov_coldest_fec'),
        ),
        migrations.AddIndex(
            model_name='movimientoactivo',
            index=models.Index(fields=['tipo_movimiento', '-fecha_movimiento'], name='idx_mov_tipo_fec'),
        ),
    ]
