# Generated by Django 5.2.17 on 2026-09-29 19:50

import uuid
from django.db import migrations, models


def backfill_unique_tokens(apps, schema_editor):
    """Every legacy row gets an independent token before the unique constraint."""
    Equipamiento = apps.get_model('core', 'Equipamiento')
    seen = set()
    for asset in Equipamiento.objects.using(schema_editor.connection.alias).order_by('pk').iterator():
        token = asset.token_qr
        if token is None or token in seen:
            token = uuid.uuid4()
            while token in seen:
                token = uuid.uuid4()
            Equipamiento.objects.using(schema_editor.connection.alias).filter(pk=asset.pk).update(token_qr=token)
        seen.add(token)



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_actaentrega_foliocontador_movimientoactivo_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_unique_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='equipamiento',
            name='token_qr',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
