# Generated by Django 5.2.17 on 2026-09-29 20:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_equipamiento_token_qr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actaentrega',
            options={'base_manager_name': 'objects', 'ordering': ['-fecha_emision', '-pk'], 'verbose_name': 'Acta de Entrega y Custodia', 'verbose_name_plural': 'Actas de Entrega y Custodia'},
        ),
        migrations.AlterModelOptions(
            name='movimientoactivo',
            options={'base_manager_name': 'objects', 'ordering': ['-fecha_movimiento', '-pk'], 'verbose_name': 'Movimiento de Activo', 'verbose_name_plural': 'Movimientos de Activos'},
        ),
        migrations.AddField(
            model_name='actaentrega',
            name='documento_pdf',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='actaentrega',
            name='snapshot_documento',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='snapshot',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='usuario_ti',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_activos_ejecutados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actaentrega',
            name='fecha_emision',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='actaentrega',
            name='hash_verificacion',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='movimientoactivo',
            name='fecha_movimiento',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='securityauditlog',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
