# Generated by Django 5.2.17 on 2026-09-29 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_actaentrega_id_alter_anexo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaentrega',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actas', to='core.usuario'),
        ),
    ]
