# Generated by Django 5.2.17 on 2026-09-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_acta_colaborador_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoactivo',
            name='operacion_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
