# Generated by Django 5.2.17 on 2026-09-30 00:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_movimiento_operacion_cambio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaEstadoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('BORRADOR', 'Borrador'), ('GENERADA', 'Generada'), ('PENDIENTE_FIRMA', 'Pendiente de firma'), ('FIRMADA', 'Firmada'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('BORRADOR', 'Borrador'), ('GENERADA', 'Generada'), ('PENDIENTE_FIRMA', 'Pendiente de firma'), ('FIRMADA', 'Firmada'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('motivo', models.TextField(blank=True, default='')),
                ('copia_firmada_pdf', models.BinaryField(null=True)),
                ('hash_copia_firmada', models.CharField(blank=True, default='', editable=False, max_length=64)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado_eventos', to='core.actaentrega')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_estado_acta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'indexes': [models.Index(fields=['acta', '-id'], name='idx_acta_estado_evento')],
            },
        ),
    ]
