# Generated by Django 5.2.17 on 2026-09-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_actaestadoevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamiento',
            name='fecha_vencimiento_garantia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='equipamiento',
            index=models.Index(fields=['fecha_vencimiento_garantia'], name='idx_equipo_garantia'),
        ),
    ]
