# Generated by Django 5.2.17 on 2026-10-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_equipamiento_fecha_vencimiento_garantia_and_more'),
    ]

    operations = [
        # Borrar las tablas dependientes completas antes de eliminar columnas:
        # SQLite reconstruye tablas al quitar campos y exige índices aún presentes.
        migrations.DeleteModel(name='ActaEstadoEvento'),
        migrations.DeleteModel(name='MovimientoActivo'),
        migrations.DeleteModel(name='ActaEntrega'),
        migrations.DeleteModel(name='FolioContador'),
        migrations.RemoveConstraint(
            model_name='equipamiento',
            name='ck_equipo_asignacion_valida',
        ),
        migrations.RemoveIndex(
            model_name='equipamiento',
            name='idx_equipo_garantia',
        ),
        migrations.RemoveField(
            model_name='equipamiento',
            name='estado_fisico',
        ),
        migrations.RemoveField(
            model_name='equipamiento',
            name='fecha_alta',
        ),
        migrations.RemoveField(
            model_name='equipamiento',
            name='fecha_vencimiento_garantia',
        ),
        migrations.RemoveField(
            model_name='equipamiento',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='equipamiento',
            name='ubicacion_actual',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='centro_costo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rut_normalizado',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ubicacion',
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='estado',
            field=models.CharField(choices=[('ASIGNADO', 'Asignado'), ('STOCK', 'Stock / Disponible'), ('MANTENCION', 'En Mantención'), ('BAJA', 'Dado de Baja')], default='ASIGNADO', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='equipamiento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado__in', ['STOCK', 'MANTENCION', 'BAJA']), ('fecha_asignacion__isnull', True), ('usuario__isnull', True)), models.Q(('estado__in', ['ASIGNADO', 'MANTENCION', 'BAJA']), ('usuario__isnull', False)), _connector='OR'), name='ck_equipo_asignacion_valida'),
        ),
    ]
