# Generated by Django 6.0.8 on 2026-10-08 12:23

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_protect_active_ip_assignment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='anexo',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='departamento',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='equipamiento',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ip',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='pcgenerico',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='perfilgenerico',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='servidor',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='subarea',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='anexo',
            name='archive_context',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='anexo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='anexo',
            name='deleted_by',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='archive_context',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='departamento',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='deleted_by',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='archive_context',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='deleted_by',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='archive_context',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='ip',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='deleted_by',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pcgenerico',
            name='archive_context',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='pcgenerico',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pcgenerico',
            name='deleted_by',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='perfilgenerico',
            name='archive_context',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='perfilgenerico',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='perfilgenerico',
            name='deleted_by',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='archive_context',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='servidor',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='deleted_by',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='subarea',
            name='archive_context',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='subarea',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='subarea',
            name='deleted_by',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='archive_context',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='deleted_by',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historialasignacionip',
            name='accion',
            field=models.CharField(choices=[('ASIGNACION', 'Asignación'), ('LIBERACION', 'Liberación'), ('MIGRACION', 'Migración inicial'), ('ARCHIVO', 'Envío a Papelera'), ('RESTAURACION', 'Restauración')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'Activo'), ('LICENCIA', 'En Licencia'), ('BAJA', 'Baja')], default='ACTIVO', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PapeleraEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=40)),
                ('registro_id', models.PositiveBigIntegerField()),
                ('accion', models.CharField(max_length=20)),
                ('realizado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-fecha', '-pk'],
                'indexes': [models.Index(fields=['modulo', 'registro_id', '-fecha'], name='idx_papelera_mod_reg_fecha')],
            },
        ),
    ]
