# Generated by Django 6.0.8 on 2026-10-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_anexo_managers_alter_departamento_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialasignacionip',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialasignacionip',
            name='accion',
            field=models.CharField(choices=[('REGISTRO', 'Registro'), ('MODIFICACION', 'Modificación'), ('ASIGNACION', 'Asignación'), ('LIBERACION', 'Liberación'), ('MIGRACION', 'Migración inicial'), ('ARCHIVO', 'Envío a Papelera'), ('RESTAURACION', 'Restauración')], max_length=20),
        ),
    ]
